import { Link } from "react-router-dom";
import { useEffect, useRef, useState } from "react";
import {
  ArrowRight, Shield, Users, ClipboardList, BookOpen,
  Settings, Hammer, Database, MessageSquare, Wrench, ChevronRight,
  Sparkles, MessageCircle,
} from "lucide-react";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { SectionPill } from "@/components/landing/shared";
import { landingColors, landingGradients } from "@/components/landing/theme";
import { getSessionRole, isTOStage3Role } from "@/data/sessionRole";

const toPrompts = [
  "How do I submit a transformation artefact request?",
  "What services does the T-Office provide?",
  "How does the Architecture Review Board work?",
  "What is the difference between Document Studio and Solution Specs?",
  "How do I get platform support?",
];

const mandate = [
  {
    label: "Govern",
    description: "Oversee all transformation request intake, prioritisation, and approval pipelines across DEWA divisions.",
  },
  {
    label: "Fulfil",
    description: "Deliver transformation artefacts, solution specifications, and expert advisory services within defined SLAs.",
  },
  {
    label: "Publish",
    description: "Publish reviewed and approved outputs to the platform — artefacts, knowledge articles, and architecture references.",
  },
  {
    label: "Maintain",
    description: "Maintain data layer integrity — capability canvas accuracy, asset mappings, and maturity scores enterprise-wide.",
  },
];

const services = [
  {
    icon: ClipboardList,
    name: "Transformation Artefact Generation",
    description: "Assessment reports, architecture design documents, application profiles, and design report requests — generated by the EA Office with defined delivery timelines.",
    pathway: "Via Transformation Artefacts (Document Studio)",
    route: "/marketplaces/document-studio",
    color: "#6d28d9",
  },
  {
    icon: Settings,
    name: "Solution Specification",
    description: "Blueprint and specification requests for in-house delivery — documented, reviewed, and published as reusable architecture assets.",
    pathway: "Via Solution Specifications",
    route: "/marketplaces/solution-specs",
    color: "#0369A1",
  },
  {
    icon: Hammer,
    name: "Solution Build",
    description: "End-to-end solution deployment requests governed through the EA Office intake process — from architecture sign-off to delivery oversight.",
    pathway: "Via Solution Build",
    route: "/marketplaces/solution-build",
    color: "#16A34A",
  },
  {
    icon: Database,
    name: "Data Corrections",
    description: "Asset record corrections, capability maturity data updates, and EA data layer integrity requests — handled with full audit trail.",
    pathway: "Via Support & Expert Services",
    route: "/marketplaces/support",
    color: "#D97706",
  },
  {
    icon: MessageSquare,
    name: "Expert Consultancy",
    description: "EA Office advisory sessions for specific capability questions, architecture decisions, or divisional transformation planning support.",
    pathway: "Via Support & Expert Services",
    route: "/marketplaces/support",
    color: "#D97706",
  },
  {
    icon: Wrench,
    name: "Platform Support",
    description: "Issue logging, access requests, and incident escalation for the DTMP platform — triaged and resolved by the T-Office administration team.",
    pathway: "Via Support & Expert Services",
    route: "/marketplaces/support",
    color: "#D97706",
  },
];

const teamRoles = [
  {
    icon: Shield,
    role: "T-Office Lead",
    responsibility: "Overall governance and programme oversight — accountable for the T-Office service SLAs, quality standards, and stakeholder reporting.",
  },
  {
    icon: ClipboardList,
    role: "Delivery Staff",
    responsibility: "Request fulfilment, transformation artefact generation, and publication — the core delivery function of the T-Office.",
  },
  {
    icon: Settings,
    role: "Administrators",
    responsibility: "Platform configuration, user access management, SLA definition, and audit trail maintenance across all T-Office workflows.",
  },
  {
    icon: BookOpen,
    role: "EA Liaison",
    responsibility: "Architecture validation and capability canvas governance — the connection point between the T-Office and the Corporate EA function.",
  },
];

export default function TransformationOfficePage() {
  const isTO = isTOStage3Role(getSessionRole());
  const [aiFocused, setAiFocused] = useState(false);
  const [aiQuery, setAiQuery] = useState("");
  const aiContainerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function handleClick(e: MouseEvent) {
      if (aiContainerRef.current && !aiContainerRef.current.contains(e.target as Node)) {
        setAiFocused(false);
      }
    }
    document.addEventListener("mousedown", handleClick);
    return () => document.removeEventListener("mousedown", handleClick);
  }, []);

  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-1">

        {/* ── Hero ── */}
        <section
          className="relative py-10 lg:py-14 flex items-center overflow-hidden"
          style={{ background: landingGradients.hero }}
        >
          <div
            className="absolute inset-0 pointer-events-none"
            style={{ background: "radial-gradient(ellipse 70% 60% at 60% 50%, rgba(255,255,255,0.04) 0%, transparent 70%)" }}
          />
          <div className="max-w-5xl mx-auto px-6 lg:px-8 relative z-10 text-center w-full">
            {/* pill */}
            <div
              className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full mb-8"
              style={{ background: "rgba(255,255,255,0.07)", border: "1px solid rgba(255,255,255,0.14)" }}
            >
              <span className="w-1.5 h-1.5 rounded-full inline-block" style={{ background: "#a7f3d0" }} />
              <span className="text-xs font-semibold uppercase tracking-widest text-white/50">
                Transformation Office
              </span>
            </div>
            <h1 className="text-5xl lg:text-6xl font-bold text-white mb-6 leading-tight tracking-tight">
              The EA{" "}
              <span style={{ background: "linear-gradient(90deg, #bbf7d0 0%, #5eead4 55%, #7dd3fc 100%)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>
                Transformation Office
              </span>
            </h1>
            <p className="text-white/60 text-lg max-w-2xl mx-auto mb-10 leading-relaxed">
              The engine behind DEWA's architecture governance — governing intake, fulfilling requests, publishing artefacts, and maintaining the data layer that underpins the entire platform.
            </p>

            {/* AI chat bar */}
            <div
              ref={aiContainerRef}
              className={`w-full mb-8 bg-white transition-all overflow-hidden ${
                aiFocused ? "rounded-2xl ring-2 ring-slate-900 shadow-xl" : "rounded-2xl shadow-lg"
              }`}
            >
              <div className={`px-6 py-5 flex items-center gap-4 ${aiFocused ? "border-b border-slate-100" : ""}`}>
                <Sparkles size={20} className="flex-shrink-0" style={{ color: landingColors.primary }} />
                <input
                  type="text"
                  value={aiQuery}
                  onChange={(e) => setAiQuery(e.target.value)}
                  onFocus={() => setAiFocused(true)}
                  placeholder="Ask me anything about the Transformation Office... What do you need help with?"
                  className="text-slate-700 text-base flex-1 text-left bg-transparent outline-none placeholder:text-slate-400"
                />
                <span className="flex items-center gap-1.5 text-xs font-semibold text-emerald-600 shrink-0">
                  <span className="w-2 h-2 rounded-full bg-emerald-500 inline-block" />
                  EA Ready
                </span>
                <div className="w-px h-5 bg-slate-200 shrink-0" />
                <MessageCircle
                  size={20}
                  className="text-slate-400 transition-colors cursor-pointer shrink-0"
                  onMouseEnter={(e) => (e.currentTarget.style.color = landingColors.teal)}
                  onMouseLeave={(e) => (e.currentTarget.style.color = "")}
                />
              </div>
              {aiFocused && (
                <div className="px-6 pt-4 pb-5 text-left">
                  <p className="text-xs font-semibold text-slate-500 flex items-center gap-1.5 mb-3">
                    <Sparkles size={13} style={{ color: landingColors.teal }} />
                    EA Assistant Examples:
                  </p>
                  <div className="flex flex-wrap gap-2 mb-4">
                    {toPrompts.map((prompt) => (
                      <button
                        key={prompt}
                        onMouseDown={() => { setAiQuery(prompt); setAiFocused(false); }}
                        className="text-sm text-slate-700 font-medium px-4 py-2 rounded-xl border border-slate-200 transition-all"
                        onMouseEnter={(e) => {
                          e.currentTarget.style.borderColor = "#86efac";
                          e.currentTarget.style.background = "#f0fdf4";
                          e.currentTarget.style.color = landingColors.primary;
                        }}
                        onMouseLeave={(e) => {
                          e.currentTarget.style.borderColor = "";
                          e.currentTarget.style.background = "";
                          e.currentTarget.style.color = "";
                        }}
                      >
                        {prompt}
                      </button>
                    ))}
                  </div>
                  <p className="text-xs flex items-center gap-1.5" style={{ color: landingColors.teal }}>
                    <Sparkles size={12} />
                    Powered by AI — I can explain features, guide you, and help you find what you need
                  </p>
                </div>
              )}
            </div>

            {/* Hero CTAs */}
            <div className="flex flex-wrap justify-center gap-4">
              <Link
                to="/marketplaces/document-studio"
                className="inline-flex items-center gap-2 px-6 py-3 rounded-xl font-semibold text-sm transition-all"
                style={{ background: "rgba(255,255,255,0.15)", border: "1.5px solid rgba(255,255,255,0.3)", color: "#fff" }}
              >
                <ClipboardList size={16} /> Submit a Request
              </Link>
              <Link
                to="/marketplaces/support"
                className="inline-flex items-center gap-2 px-6 py-3 rounded-xl font-semibold text-sm text-white transition-all"
                style={{ background: landingGradients.secondary }}
              >
                Browse Service Catalogue <ArrowRight size={16} />
              </Link>
            </div>
          </div>
        </section>

        {/* ── Mandate ── */}
        <section className="py-20 bg-white">
          <div className="max-w-5xl mx-auto px-6 lg:px-8">
            <div className="text-center mb-12">
              <SectionPill label="Our Mandate" />
              <h2 className="text-3xl lg:text-4xl font-bold text-slate-900 mb-3">What the T-Office Exists To Do</h2>
              <p className="text-slate-500 text-sm max-w-2xl mx-auto leading-relaxed">
                The Transformation Office is the operational arm of DEWA's Corporate EA function — turning governance policy into delivered outcomes across every division.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-10">
              {mandate.map((item, i) => (
                <div
                  key={i}
                  className="bg-white rounded-2xl p-6 border border-slate-100 shadow-sm text-center transition-all"
                  onMouseEnter={e => (e.currentTarget.style.boxShadow = "6px 8px 24px rgba(6,95,70,0.16)")}
                  onMouseLeave={e => (e.currentTarget.style.boxShadow = "")}
                >
                  <div
                    className="w-14 h-14 rounded-xl flex items-center justify-center mx-auto mb-4 text-white text-xl font-black"
                    style={{ background: landingGradients.secondary }}
                  >
                    {item.label[0]}
                  </div>
                  <h3 className="font-bold text-slate-900 mb-2 text-base">{item.label}</h3>
                  <p className="text-slate-500 text-sm leading-relaxed">{item.description}</p>
                </div>
              ))}
            </div>

            {/* Governance scope summary */}
            <div className="rounded-2xl p-6 border border-slate-100 bg-slate-50">
              <p className="text-xs font-bold uppercase tracking-widest text-slate-400 mb-2">Governance Scope</p>
              <p className="text-slate-700 text-sm leading-relaxed">
                The T-Office oversees the full transformation request lifecycle — artefact generation, initiative governance, data layer integrity, and programme quality — across all DEWA divisions. Every artefact published through the DTMP has been reviewed and approved by the T-Office before reaching the marketplace.
              </p>
            </div>
          </div>
        </section>

        {/* ── Service Catalogue ── */}
        <section className="py-20" style={{ background: landingColors.surface }}>
          <div className="max-w-5xl mx-auto px-6 lg:px-8">
            <div className="text-center mb-12">
              <SectionPill label="Service Catalogue" />
              <h2 className="text-3xl lg:text-4xl font-bold text-slate-900 mb-3">What You Can Request</h2>
              <p className="text-slate-500 text-sm max-w-xl mx-auto leading-relaxed">
                Six categories of service available to all DEWA divisions — each with a defined request pathway through the platform.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {services.map((svc, i) => {
                const Icon = svc.icon;
                return (
                  <div
                    key={i}
                    className="bg-white rounded-2xl p-6 border border-slate-100 shadow-sm flex flex-col transition-all"
                    onMouseEnter={e => (e.currentTarget.style.boxShadow = "6px 8px 24px rgba(6,95,70,0.16)")}
                    onMouseLeave={e => (e.currentTarget.style.boxShadow = "")}
                  >
                    <div
                      className="w-11 h-11 rounded-xl flex items-center justify-center mb-4 text-white shrink-0"
                      style={{ background: svc.color }}
                    >
                      <Icon size={20} />
                    </div>
                    <h3 className="font-bold text-slate-900 mb-2 text-base leading-tight">{svc.name}</h3>
                    <p className="text-slate-500 text-sm leading-relaxed flex-1 mb-4">{svc.description}</p>
                    <div className="border-t border-slate-100 pt-4">
                      <p className="text-xs text-slate-400 mb-2">{svc.pathway}</p>
                      <Link
                        to={svc.route}
                        className="text-sm font-semibold inline-flex items-center gap-1 hover:underline transition-colors"
                        style={{ color: svc.color }}
                      >
                        Submit a request <ArrowRight size={13} />
                      </Link>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </section>

        {/* ── Team Structure ── */}
        <section className="py-20 bg-white">
          <div className="max-w-5xl mx-auto px-6 lg:px-8">
            <div className="text-center mb-12">
              <SectionPill label="Team Structure" />
              <h2 className="text-3xl lg:text-4xl font-bold text-slate-900 mb-3">Who Makes the T-Office Work</h2>
              <p className="text-slate-500 text-sm max-w-xl mx-auto leading-relaxed">
                Four roles, each accountable for a distinct function in the transformation fulfilment pipeline.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {teamRoles.map((role, i) => {
                const Icon = role.icon;
                return (
                  <div
                    key={i}
                    className="flex items-start gap-5 bg-white rounded-2xl p-6 border border-slate-100 shadow-sm"
                  >
                    <div
                      className="w-12 h-12 rounded-xl flex items-center justify-center shrink-0 text-white"
                      style={{ background: landingGradients.secondary }}
                    >
                      <Icon size={20} />
                    </div>
                    <div>
                      <h3 className="font-bold text-slate-900 mb-1.5">{role.role}</h3>
                      <p className="text-slate-500 text-sm leading-relaxed">{role.responsibility}</p>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </section>

        {/* ── Engagement CTAs ── */}
        <section
          className="py-16"
          style={{ background: landingGradients.darkCta }}
        >
          <div className="max-w-6xl mx-auto px-6 lg:px-8 flex flex-col lg:flex-row items-start lg:items-center gap-10">
            <div className="flex-1">
              <h2 className="text-3xl font-bold text-white mb-2">
                Engage with the{" "}
                <span style={{ color: "#a7f3d0" }}>Transformation Office</span>
              </h2>
              <div className="w-10 h-0.5 bg-white/30 mb-4" />
              <p className="text-white/60 text-sm">
                Submit a request, browse the service catalogue, or — if you're T-Office staff — enter your governance dashboard.
              </p>
            </div>
            <div className="flex flex-col gap-3 w-full lg:w-96">
              <Link
                to="/marketplaces/document-studio"
                className="flex items-center justify-between px-5 py-3.5 rounded-xl text-sm font-semibold text-white transition-all hover:bg-white/20"
                style={{ background: "rgba(255,255,255,0.10)", border: "1px solid rgba(255,255,255,0.15)" }}
              >
                <span className="flex items-center gap-3"><ClipboardList size={16} /> Submit a Request</span>
                <ChevronRight size={16} className="text-white/50" />
              </Link>
              <Link
                to="/marketplaces/support"
                className="flex items-center justify-between px-5 py-3.5 rounded-xl text-sm font-semibold text-white transition-all hover:bg-white/20"
                style={{ background: "rgba(255,255,255,0.10)", border: "1px solid rgba(255,255,255,0.15)" }}
              >
                <span className="flex items-center gap-3"><BookOpen size={16} /> Browse Service Catalogue</span>
                <ChevronRight size={16} className="text-white/50" />
              </Link>
              {isTO ? (
                <Link
                  to="/stage3/dashboard"
                  className="flex items-center justify-between px-5 py-3.5 rounded-xl text-sm font-semibold text-white transition-all hover:opacity-90"
                  style={{ background: landingGradients.secondary }}
                >
                  <span className="flex items-center gap-3"><Users size={16} /> Enter the Transformation Office</span>
                  <ArrowRight size={16} />
                </Link>
              ) : (
                <span
                  className="flex items-center justify-between px-5 py-3.5 rounded-xl text-sm font-semibold text-white/30 cursor-not-allowed"
                  style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)" }}
                  title="Restricted to Transformation Office staff"
                >
                  <span className="flex items-center gap-3"><Users size={16} /> Enter the Transformation Office</span>
                  <span className="text-xs text-white/20">T-Office only</span>
                </span>
              )}
            </div>
          </div>
        </section>

      </main>
      <Footer />
    </div>
  );
}
